translation article about data driven test
august-alt/cpp_articles pull request #24
Opened 2022-06-09 14:23 UTC by AlexSP0

translation article about data driven test

2022-06-09 15:15 UTC, AntProBasealt commented on data_driven_test.md
> +
Закрывающие ```

2022-06-10 11:59 UTC, august-alt requested changes

2022-06-10 11:59 UTC, august-alt commented on data_driven_test.md
> +Для того, чтобы избежать повторения кода, QT тесты подддреживают добавление данных для проведения тестов. Все, что нам надо, это добавить другой приватный слот в наш тестовый класс:
подддреживают -> поддреживают

2022-06-10 11:59 UTC, august-alt commented on data_driven_test.md
> +Функция для добавления данных к тесту носит тоже имя с добавлением _data. Наша функция добавления данных выглядит так:
Функция данных, связанная с тестовой функцией, имеет такое же имя как и тестовая функция, к которому добавляется суффикс _data.

2022-06-10 11:59 UTC, august-alt commented on data_driven_test.md
> +#include "testqstring.moc"
Мы используем CMake у нас не используются moc файлы.

2022-06-22 13:42 UTC, closed without merging